// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221103023317_incluindo_campo_accepted")]
    partial class incluindo_campo_accepted
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Entidades.Gerenciamento_Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Accepted")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(1)")
                        .HasDefaultValue("A");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Contact_Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Contact_First_Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Contact_Full_Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Contact_Phone_Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Gerenciamento_Leads");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1b409c92-e2cc-450e-a4d5-7088e7a105e7"),
                            Accepted = "A",
                            Category = "Seriço doméstico",
                            Contact_Email = "joao@hotmail.com",
                            Contact_First_Name = "João",
                            Contact_Full_Name = "João da Silva",
                            Contact_Phone_Number = "55-21-988776655",
                            Date_Created = new DateTime(2022, 11, 3, 2, 33, 17, 301, DateTimeKind.Utc).AddTicks(6079),
                            Description = "Descrição xxxxxxxxxxxxxxxxxx",
                            Price = 20m,
                            Suburb = "Não sei"
                        },
                        new
                        {
                            Id = new Guid("e9a0d685-300d-4626-94d1-74ea56e59c05"),
                            Accepted = "A",
                            Category = "Pintura",
                            Contact_Email = "cbarbosa@icloud.com",
                            Contact_First_Name = "Carlos",
                            Contact_Full_Name = "Carlos Barbosa",
                            Contact_Phone_Number = "55-98-987660011",
                            Date_Created = new DateTime(2022, 11, 3, 2, 33, 17, 301, DateTimeKind.Utc).AddTicks(6083),
                            Description = "Descrição xxxxxxxxxxxxxxxxxx",
                            Price = 100m,
                            Suburb = "Não sei"
                        },
                        new
                        {
                            Id = new Guid("8d98436d-53b5-4a82-9a0a-fed3a769e766"),
                            Accepted = "A",
                            Category = "Diarista",
                            Contact_Email = "anaoliveira@gmail.com",
                            Contact_First_Name = "Ana Maria",
                            Contact_Full_Name = "Ana Maria Oliveira",
                            Contact_Phone_Number = "55-91-987785544",
                            Date_Created = new DateTime(2022, 11, 3, 2, 33, 17, 301, DateTimeKind.Utc).AddTicks(6085),
                            Description = "Descrição xxxxxxxxxxxxxxxxxx",
                            Price = 50m,
                            Suburb = "Não sei"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
