// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Entidades.Gerenciamento_Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Contact_Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Contact_First_Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Contact_Full_Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Contact_Phone_Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Gerenciamento_Leads");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2c0b47c5-f2ff-4aa2-9987-b21fbc63060a"),
                            Category = "Seriço doméstico",
                            Contact_Email = "joao@hotmail.com",
                            Contact_First_Name = "João",
                            Contact_Full_Name = "João da Silva",
                            Contact_Phone_Number = "55-21-988776655",
                            Date_Created = new DateTime(2022, 11, 2, 22, 54, 51, 585, DateTimeKind.Utc).AddTicks(4487),
                            Description = "Descrição xxxxxxxxxxxxxxxxxx",
                            Price = 20m,
                            Suburb = "Não sei"
                        },
                        new
                        {
                            Id = new Guid("c4fc386c-b035-4d11-a529-a3756e79073d"),
                            Category = "Pintura",
                            Contact_Email = "cbarbosa@icloud.com",
                            Contact_First_Name = "Carlos",
                            Contact_Full_Name = "Carlos Barbosa",
                            Contact_Phone_Number = "55-98-987660011",
                            Date_Created = new DateTime(2022, 11, 2, 22, 54, 51, 585, DateTimeKind.Utc).AddTicks(4495),
                            Description = "Descrição xxxxxxxxxxxxxxxxxx",
                            Price = 100m,
                            Suburb = "Não sei"
                        },
                        new
                        {
                            Id = new Guid("e0ca63af-ea15-4e22-bbc7-9379ad4917e9"),
                            Category = "Diarista",
                            Contact_Email = "anaoliveira@gmail.com",
                            Contact_First_Name = "Ana Maria",
                            Contact_Full_Name = "Ana Maria Oliveira",
                            Contact_Phone_Number = "55-91-987785544",
                            Date_Created = new DateTime(2022, 11, 2, 22, 54, 51, 585, DateTimeKind.Utc).AddTicks(4497),
                            Description = "Descrição xxxxxxxxxxxxxxxxxx",
                            Price = 50m,
                            Suburb = "Não sei"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
